# Generated by Django 4.2.11 on 2024-04-18 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_main',
        ),
    ]
