# Generated by Django 4.2.11 on 2024-04-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
